stages:
  setup_env:
    cmd: ./scripts/setup.sh 1
    deps:
    - ./scripts/setup.sh
    always_changed: true
  dl_quail:
    cmd: ./src/etl/dl_quail.sh
    deps:
    - src/etl/dl_quail.sh
    outs:
    - data/quail/dev.json
    - data/quail/dev_answers.json
    - data/quail/eval.py
    - data/quail/train.json
    - data/quail/train_answers.json
  dl_models:
    cmd: python ./src/etl/dl_models.py -m bert-large-uncased bert-base-uncased bert-base-multilingual-cased
      --overwrite
    deps:
    - src/etl/dl_models.py
    outs:
    - data/models/bert-base-multilingual-cased
    - data/models/bert-base-uncased
    - data/models/bert-large-uncased
  tr_quail_train_to_race:
    cmd: src/etl/preprocess_quail_to_race.py data/quail/train.json data/quail/train_answers.json
      -o data/quail_race_fmt/train.json
    deps:
    - data/quail/train.json
    - data/quail/train_answers.json
    - src/etl/preprocess_quail_to_race.py
    outs:
    - data/quail_race_fmt/train.json
  tr_quail_dev_to_race:
    cmd: src/etl/preprocess_quail_to_race.py data/quail/dev.json data/quail/dev_answers.json
      -o data/quail_race_fmt/dev.json
    deps:
    - data/quail/dev.json
    - data/quail/dev_answers.json
    - src/etl/preprocess_quail_to_race.py
    outs:
    - data/quail_race_fmt/dev.json
  60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384:
    cmd: ./src/processing/run.sh data/specs/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384_experiment.json
    deps:
    - data/models/bert-base-uncased
    - data/quail/dev_race_fmt.json
    - data/quail/train_race_fmt.json
    - src/processing/run.sh
    params:
    - data/specs/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384_experiment.json:
      - params.do_eval
      - params.do_train
      - params.fp16
      - params.fp16_opt_level
      - params.gradient_accumulation_steps
      - params.learning_rate
      - params.max_seq_length
      - params.meta
      - params.model_type
      - params.num_train_epochs
      - params.task_name
    outs:
    - data/models/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384/config.json
    - data/models/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384/pytorch_model.bin
    - data/models/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384/special_tokens_map.json
    - data/models/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384/tokenizer_config.json
    - data/models/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384/training_args.bin
    - data/models/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384/vocab.txt
    - data/results/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384/eval_nbest_predictions.json
    - data/results/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384/eval_predictions.json
    metrics:
    - data/metrics/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384/eval_metrics.json
  4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df:
    cmd: ./src/processing/run.sh data/specs/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df_experiment.json
    deps:
    - data/models/bert-base-uncased
    - data/quail/dev_race_fmt.json
    - data/quail/train_race_fmt.json
    - src/processing/run.sh
    params:
    - data/specs/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df_experiment.json:
      - params.do_eval
      - params.do_train
      - params.fp16
      - params.fp16_opt_level
      - params.gradient_accumulation_steps
      - params.learning_rate
      - params.max_seq_length
      - params.meta
      - params.model_type
      - params.num_train_epochs
      - params.task_name
    outs:
    - data/models/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df/config.json
    - data/models/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df/pytorch_model.bin
    - data/models/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df/special_tokens_map.json
    - data/models/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df/tokenizer_config.json
    - data/models/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df/training_args.bin
    - data/models/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df/vocab.txt
    - data/results/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df/eval_nbest_predictions.json
    - data/results/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df/eval_predictions.json
    metrics:
    - data/metrics/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df/eval_metrics.json
  4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df_evaluation:
    cmd: mcqa_utils -d data/quail_race_fmt -n data/results/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df/eval_nbest_predictions.json
      --split dev --task generic -ft --metrics C_at_1 avg --output data/metrics/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df/evaluation.json
    deps:
    - data/quail_race_fmt/dev.json
    - data/results/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df/eval_nbest_predictions.json
    metrics:
    - data/metrics/4819225caddd2f92c878079d1b17e675eeb5d704de41996605ad6cdb7afc70df/evaluation.json
  60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384_evaluation:
    cmd: mcqa_utils -d data/quail_race_fmt -n data/results/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384/eval_nbest_predictions.json
      --split dev --task generic -ft --metrics C_at_1 avg --output data/metrics/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384/evaluation.json
    deps:
    - data/quail_race_fmt/dev.json
    - data/results/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384/eval_nbest_predictions.json
    metrics:
    - data/metrics/60d988dee30ae86536ee58ea2777c69747316251fb6a4e9d2623be788f4a6384/evaluation.json
  4888f3b8bec2c7ea4eb89d07ac877fc0c19aa15bbfa74c1bc32c5170abcb8482:
    cmd: ./src/processing/run.sh data/specs/4888f3b8bec2c7ea4eb89d07ac877fc0c19aa15bbfa74c1bc32c5170abcb8482_experiment.json
    deps:
    - data/models/eee4b9c4ecad29f96b656c5c85af637ab919d0ac561a95d0914203925d8f4561
    - data/quail/dev_race_fmt.json
    - src/processing/run.sh
    params:
    - data/specs/4888f3b8bec2c7ea4eb89d07ac877fc0c19aa15bbfa74c1bc32c5170abcb8482_experiment.json:
      - params.do_eval
      - params.fp16
      - params.fp16_opt_level
      - params.gradient_accumulation_steps
      - params.learning_rate
      - params.max_seq_length
      - params.meta
      - params.model_type
      - params.num_train_epochs
      - params.task_name
    outs:
    - data/results/4888f3b8bec2c7ea4eb89d07ac877fc0c19aa15bbfa74c1bc32c5170abcb8482/eval_nbest_predictions.json
    - data/results/4888f3b8bec2c7ea4eb89d07ac877fc0c19aa15bbfa74c1bc32c5170abcb8482/eval_predictions.json
    metrics:
    - data/metrics/4888f3b8bec2c7ea4eb89d07ac877fc0c19aa15bbfa74c1bc32c5170abcb8482/eval_metrics.json
  94348d79ad84fec361b4d7c5030331591ca70d07b26836691880ae1939f18021:
    cmd: ./src/processing/run.sh data/specs/94348d79ad84fec361b4d7c5030331591ca70d07b26836691880ae1939f18021_experiment.json
    deps:
    - data/models/12942b9ce5eb231bd51d867a17ff9b243de813ae44de6056b5066ac67a7131b2
    - data/quail/dev_race_fmt.json
    - src/processing/run.sh
    params:
    - data/specs/94348d79ad84fec361b4d7c5030331591ca70d07b26836691880ae1939f18021_experiment.json:
      - params.do_eval
      - params.fp16
      - params.fp16_opt_level
      - params.gradient_accumulation_steps
      - params.learning_rate
      - params.max_seq_length
      - params.meta
      - params.model_type
      - params.num_train_epochs
      - params.task_name
    outs:
    - data/results/94348d79ad84fec361b4d7c5030331591ca70d07b26836691880ae1939f18021/eval_nbest_predictions.json
    - data/results/94348d79ad84fec361b4d7c5030331591ca70d07b26836691880ae1939f18021/eval_predictions.json
    metrics:
    - data/metrics/94348d79ad84fec361b4d7c5030331591ca70d07b26836691880ae1939f18021/eval_metrics.json
