stages:
  dl_quail:
    cmd: ./src/etl/dl_quail.sh
    deps:
    - src/etl/dl_quail.sh
    outs:
    - data/quail/dev.json
    - data/quail/dev_answers.json
    - data/quail/eval.py
    - data/quail/train.json
    - data/quail/train_answers.json
  dl_models:
    cmd: python ./src/etl/dl_models.py -m bert-base-uncased --overwrite
    deps:
    - src/etl/dl_models.py
    outs:
    - data/models/bert-base-uncased
  tr_quail_train_to_race:
    cmd: src/etl/preprocess_quail_to_race.py data/quail/train.json data/quail/train_answers.json
      -o data/quail_race_fmt/train.json
    deps:
    - data/quail/train.json
    - data/quail/train_answers.json
    - src/etl/preprocess_quail_to_race.py
    outs:
    - data/quail_race_fmt/train.json
  tr_quail_dev_to_race:
    cmd: src/etl/preprocess_quail_to_race.py data/quail/dev.json data/quail/dev_answers.json
      -o data/quail_race_fmt/dev.json
    deps:
    - data/quail/dev.json
    - data/quail/dev_answers.json
    - src/etl/preprocess_quail_to_race.py
    outs:
    - data/quail_race_fmt/dev.json
  tr_quail_train_no_empty_answers:
    cmd: python src/etl/choices/reformat_dataset.py -d data/quail_race_fmt -o data/quail_no_empty_answers
      -s train --no_answer_text "not enough information"
    deps:
    - data/quail_race_fmt
    - src/etl/choices/reformat_dataset.py
    outs:
    - data/quail_no_empty_answers/train.json
  tr_quail_dev_no_empty_answers:
    cmd: python src/etl/choices/reformat_dataset.py -d ./data/quail_race_fmt -o ./data/quail_no_empty_answers
      -s dev --no_answer_text "not enough information" --keep_matching_text --index_list_path
      ./data/quail_no_empty_answers/dev_index_list.json
    deps:
    - data/quail_race_fmt
    - src/etl/choices/reformat_dataset.py
    outs:
    - ./data/quail_no_empty_answers/dev_index_list.json
    - data/quail_no_empty_answers/dev.json
  bert-train-no-empty-answers:
    cmd: ./src/processing/run.sh data/specs/bert-train-no-empty-answers_experiment.json
    deps:
    - data/models/bert-base-uncased
    - data/quail_no_empty_answers/dev.json
    - data/quail_no_empty_answers/train.json
    - src/processing/run.sh
    params:
    - data/specs/bert-train-no-empty-answers_experiment.json:
      - params.do_eval
      - params.do_train
      - params.fp16
      - params.fp16_opt_level
      - params.gradient_accumulation_steps
      - params.learning_rate
      - params.max_seq_length
      - params.meta
      - params.model_type
      - params.num_train_epochs
      - params.per_device_eval_batch_size
      - params.per_device_train_batch_size
      - params.task_name
      - params.warmup_steps
    outs:
    - data/models/bert-train-no-empty-answers/config.json
    - data/models/bert-train-no-empty-answers/pytorch_model.bin
    - data/models/bert-train-no-empty-answers/special_tokens_map.json
    - data/models/bert-train-no-empty-answers/tokenizer_config.json
    - data/models/bert-train-no-empty-answers/training_args.bin
    - data/models/bert-train-no-empty-answers/vocab.txt
    - data/results/bert-train-no-empty-answers/eval_nbest_predictions.json
    - data/results/bert-train-no-empty-answers/eval_predictions.json
    - data/results/bert-train-no-empty-answers/train_nbest_predictions.json
    - data/results/bert-train-no-empty-answers/train_predictions.json
    metrics:
    - data/metrics/bert-train-no-empty-answers/eval_metrics.json
    - data/metrics/bert-train-no-empty-answers/train_metrics.json
  bert-eval-no-empty-answers:
    cmd: ./src/processing/run.sh data/specs/bert-eval-no-empty-answers_experiment.json
    deps:
    - data/models/bert-train-no-empty-answers
    - data/quail_no_empty_answers/dev.json
    - src/processing/run.sh
    params:
    - data/specs/bert-eval-no-empty-answers_experiment.json:
      - params.do_eval
      - params.fp16
      - params.fp16_opt_level
      - params.gradient_accumulation_steps
      - params.learning_rate
      - params.max_seq_length
      - params.meta
      - params.model_type
      - params.num_train_epochs
      - params.per_device_eval_batch_size
      - params.per_device_train_batch_size
      - params.task_name
      - params.warmup_steps
    outs:
    - data/results/bert-eval-no-empty-answers/eval_nbest_predictions.json
    - data/results/bert-eval-no-empty-answers/eval_predictions.json
    metrics:
    - data/metrics/bert-eval-no-empty-answers/eval_metrics.json
