classification:
    iterations: 200
    popsize: 50
    selection: 10
    early_stop: 6
    balanced: false
    memory: 64
    autogoal: false
    pipeline: mlp
    sweep_features: false
    test_size: 0.2
    metric: weighted_f1
    multi_layer:
        lr: 0.001
        epochs: 100
        batch_size: 200
features:
    normalization: true
    oversample: true
    text_length: true
    embeddings: true
    logits: true
    context: true
    question: true
    endings: true
