classification:
    iterations: 200
    popsize: 50
    selection: 10
    early_stop: 6
    balanced: false
    memory: 32
    autogoal: false
    pipeline: logreg 
    sweep_features: false
    test_size: 0.20
    multi_layer:
        lr: 0.001
        epochs: 100
        batch_size: 200
